// list location at Viet Nam
module.exports = [
  'An Giang',
  'Ba Ria-Vung Tau',
  'Bac Giang',
  'Bac Kan',
  'Ha Noi',
  'Hai Phong',
  'Hai Duong',
  'Hoa Binh',
  'Hung Yen',
  'Khanh Hoa',
  'Kien Giang',
  'Kon Tum',
  'Lai Chau',
  'Lam Dong',
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Indianapolis',
  'Columbus',
  'Fort Worth',
  'Charlotte',
  'Seattle',
  'Denver',
  'El Paso',
  'Ho Chi Minh',
  'Da Nang',
  'Can Tho',
];
